import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                background: '#f8f9ff',
                surface: '#f8f9ff',
                'surface-dim': '#cbdbf5',
                'surface-bright': '#f8f9ff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#eff4ff',
                'surface-container': '#e5eeff',
                'surface-container-high': '#dce9ff',
                'surface-container-highest': '#d3e4fe',
                'surface-variant': '#d3e4fe',
                'on-surface': '#0b1c30',
                'on-surface-variant': '#444651',
                'on-background': '#0b1c30',
                'inverse-surface': '#213145',
                'inverse-on-surface': '#eaf1ff',
                outline: '#757682',
                'outline-variant': '#c5c5d3',
                'surface-tint': '#4059aa',
                primary: '#00236f',
                'on-primary': '#ffffff',
                'primary-container': '#1e3a8a',
                'on-primary-container': '#90a8ff',
                'inverse-primary': '#b6c4ff',
                'primary-fixed': '#dce1ff',
                'primary-fixed-dim': '#b6c4ff',
                'on-primary-fixed': '#00164e',
                'on-primary-fixed-variant': '#264191',
                secondary: '#006b5f',
                'on-secondary': '#ffffff',
                'secondary-container': '#6df5e1',
                'on-secondary-container': '#006f64',
                'secondary-fixed': '#71f8e4',
                'secondary-fixed-dim': '#4fdbc8',
                'on-secondary-fixed': '#00201c',
                'on-secondary-fixed-variant': '#005048',
                tertiary: '#0d0097',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#2724b8',
                'on-tertiary-container': '#a1a4ff',
                error: '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
                'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
                'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '500' }],
                'label-sm': ['12px', { lineHeight: '1', fontWeight: '600' }],
            },
            borderRadius: {
                xl: '0.75rem',
                '2xl': '1rem',
            },
            spacing: {
                gutter: '16px',
                'container-margin': '24px',
            },
            boxShadow: {
                card: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
                elevated: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
            },
        },
    },
    plugins: [forms],
};
